/*
# Pooja Palace — Complete Database Schema

## Overview
Creates the full schema for a Hindu spiritual and Vedic pooja booking platform where users discover and book poojas at sacred destinations across India. Same pooja can have different prices at different locations via a location_poojas offering table.

## New Tables (11 total)

1. **user_profiles** — Extended user info linked to auth.users (name, phone, profile image)
2. **states** — Indian states (Uttarakhand, Uttar Pradesh, etc.)
3. **locations** — Destinations/cities/religious places, hierarchical (state → location → sub-location)
4. **categories** — Pooja categories (Pooja, Havan, Jap, Path, Shanti/Dosha, etc.)
5. **purposes** — Why a pooja is performed (New Home, Marriage, Pitri/Ancestors, etc.)
6. **deities** — Hindu deities (Shiva, Vishnu, Ganesh, Durga, Lakshmi, etc.)
7. **occasions** — Life events (New Home, Marriage, Child, Navratri, etc.)
8. **poojas** — Master pooja records with category/purpose/deity/occasion relationships
9. **location_poojas** — Location-specific offerings (price, duration, availability per location per pooja)
10. **bookings** — Booking requests with status workflow (PENDING → CONFIRMED → COMPLETED / CANCELLED)
11. **notifications** — User notifications for booking status changes

## Junction Tables
- pooja_categories, pooja_purposes, pooja_deities, pooja_occasions — many-to-many relationships

## Security
- RLS enabled on ALL tables
- Public data (states, locations, categories, purposes, deities, occasions, poojas, location_poojas) → readable by anon + authenticated
- User-specific data (user_profiles, bookings, notifications) → owner-scoped (authenticated, auth.uid() = user_id)
- Admin data (write operations on all tables) → managed via service role key from edge functions, or admin RLS via app metadata
- Booking number auto-generated via database function + trigger (PP-YYYY-NNNNN format)

## Important Notes
1. user_profiles.user_id defaults to auth.uid() so inserts work without explicitly passing user_id
2. bookings.user_id defaults to auth.uid() for the same reason
3. bookings.booking_number auto-generated by trigger using generate_booking_number() function
4. All foreign keys use ON DELETE RESTRICT on poojas/locations to preserve historical booking integrity
5. location_poojas has a unique constraint on (location_id, pooja_id) to prevent duplicate offerings
6. Admin access is controlled via raw_app_meta_data ->> 'role' = 'admin' check in RLS policies
*/

-- ============================================================
-- 1. USER PROFILES
-- ============================================================
CREATE TABLE IF NOT EXISTS user_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT '',
  phone text DEFAULT '',
  email text DEFAULT '',
  profile_image text DEFAULT '',
  address text DEFAULT '',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_profile" ON user_profiles;
CREATE POLICY "select_own_profile" ON user_profiles FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_profile" ON user_profiles;
CREATE POLICY "insert_own_profile" ON user_profiles FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_profile" ON user_profiles;
CREATE POLICY "update_own_profile" ON user_profiles FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- 2. STATES
-- ============================================================
CREATE TABLE IF NOT EXISTS states (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text DEFAULT '',
  image text DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE states ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_states" ON states;
CREATE POLICY "public_read_states" ON states FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_write_states" ON states;
CREATE POLICY "admin_write_states" ON states FOR ALL
  TO authenticated
  USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- ============================================================
-- 3. LOCATIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS locations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL,
  state_id uuid REFERENCES states(id) ON DELETE RESTRICT,
  parent_location_id uuid REFERENCES locations(id) ON DELETE SET NULL,
  type text NOT NULL DEFAULT 'city',
  description text DEFAULT '',
  significance text DEFAULT '',
  image text DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(slug, state_id)
);

ALTER TABLE locations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_locations" ON locations;
CREATE POLICY "public_read_locations" ON locations FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_write_locations" ON locations;
CREATE POLICY "admin_write_locations" ON locations FOR ALL
  TO authenticated
  USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- ============================================================
-- 4. CATEGORIES
-- ============================================================
CREATE TABLE IF NOT EXISTS categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_categories" ON categories;
CREATE POLICY "public_read_categories" ON categories FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_write_categories" ON categories;
CREATE POLICY "admin_write_categories" ON categories FOR ALL
  TO authenticated
  USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- ============================================================
-- 5. PURPOSES
-- ============================================================
CREATE TABLE IF NOT EXISTS purposes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text DEFAULT '',
  icon text DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE purposes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_purposes" ON purposes;
CREATE POLICY "public_read_purposes" ON purposes FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_write_purposes" ON purposes;
CREATE POLICY "admin_write_purposes" ON purposes FOR ALL
  TO authenticated
  USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- ============================================================
-- 6. DEITIES
-- ============================================================
CREATE TABLE IF NOT EXISTS deities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE deities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_deities" ON deities;
CREATE POLICY "public_read_deities" ON deities FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_write_deities" ON deities;
CREATE POLICY "admin_write_deities" ON deities FOR ALL
  TO authenticated
  USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- ============================================================
-- 7. OCCASIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS occasions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE occasions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_occasions" ON occasions;
CREATE POLICY "public_read_occasions" ON occasions;
CREATE POLICY "public_read_occasions" ON occasions FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_write_occasions" ON occasions;
CREATE POLICY "admin_write_occasions" ON occasions FOR ALL
  TO authenticated
  USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- ============================================================
-- 8. POOJAS
-- ============================================================
CREATE TABLE IF NOT EXISTS poojas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text DEFAULT '',
  long_description text DEFAULT '',
  image text DEFAULT '',
  duration text DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE poojas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_poojas" ON poojas;
CREATE POLICY "public_read_poojas" ON poojas FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_write_poojas" ON poojas;
CREATE POLICY "admin_write_poojas" ON poojas FOR ALL
  TO authenticated
  USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- ============================================================
-- 8a. JUNCTION TABLES (many-to-many)
-- ============================================================
CREATE TABLE IF NOT EXISTS pooja_categories (
  pooja_id uuid NOT NULL REFERENCES poojas(id) ON DELETE CASCADE,
  category_id uuid NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  PRIMARY KEY (pooja_id, category_id)
);

ALTER TABLE pooja_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_pooja_categories" ON pooja_categories;
CREATE POLICY "public_read_pooja_categories" ON pooja_categories FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_write_pooja_categories" ON pooja_categories;
CREATE POLICY "admin_write_pooja_categories" ON pooja_categories FOR ALL
  TO authenticated
  USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

CREATE TABLE IF NOT EXISTS pooja_purposes (
  pooja_id uuid NOT NULL REFERENCES poojas(id) ON DELETE CASCADE,
  purpose_id uuid NOT NULL REFERENCES purposes(id) ON DELETE CASCADE,
  PRIMARY KEY (pooja_id, purpose_id)
);

ALTER TABLE pooja_purposes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_pooja_purposes" ON pooja_purposes;
CREATE POLICY "public_read_pooja_purposes" ON pooja_purposes FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_write_pooja_purposes" ON pooja_purposes;
CREATE POLICY "admin_write_pooja_purposes" ON pooja_purposes FOR ALL
  TO authenticated
  USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

CREATE TABLE IF NOT EXISTS pooja_deities (
  pooja_id uuid NOT NULL REFERENCES poojas(id) ON DELETE CASCADE,
  deity_id uuid NOT NULL REFERENCES deities(id) ON DELETE CASCADE,
  PRIMARY KEY (pooja_id, deity_id)
);

ALTER TABLE pooja_deities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_pooja_deities" ON pooja_deities;
CREATE POLICY "public_read_pooja_deities" ON pooja_deities FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_write_pooja_deities" ON pooja_deities;
CREATE POLICY "admin_write_pooja_deities" ON pooja_deities FOR ALL
  TO authenticated
  USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

CREATE TABLE IF NOT EXISTS pooja_occasions (
  pooja_id uuid NOT NULL REFERENCES poojas(id) ON DELETE CASCADE,
  occasion_id uuid NOT NULL REFERENCES occasions(id) ON DELETE CASCADE,
  PRIMARY KEY (pooja_id, occasion_id)
);

ALTER TABLE pooja_occasions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_pooja_occasions" ON pooja_occasions;
CREATE POLICY "public_read_pooja_occasions" ON pooja_occasions FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_write_pooja_occasions" ON pooja_occasions;
CREATE POLICY "admin_write_pooja_occasions" ON pooja_occasions FOR ALL
  TO authenticated
  USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- ============================================================
-- 9. LOCATION_POOJAS (Offerings — location-specific pricing)
-- ============================================================
CREATE TABLE IF NOT EXISTS location_poojas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id uuid NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
  pooja_id uuid NOT NULL REFERENCES poojas(id) ON DELETE RESTRICT,
  price numeric(10,2) DEFAULT NULL,
  duration text DEFAULT '',
  description text DEFAULT '',
  is_available boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(location_id, pooja_id)
);

ALTER TABLE location_poojas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_location_poojas" ON location_poojas;
CREATE POLICY "public_read_location_poojas" ON location_poojas FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_write_location_poojas" ON location_poojas;
CREATE POLICY "admin_write_location_poojas" ON location_poojas FOR ALL
  TO authenticated
  USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- ============================================================
-- 10. BOOKINGS
-- ============================================================
CREATE TABLE IF NOT EXISTS bookings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_number text UNIQUE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  pooja_id uuid NOT NULL REFERENCES poojas(id) ON DELETE RESTRICT,
  location_id uuid NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
  offering_id uuid REFERENCES location_poojas(id) ON DELETE SET NULL,
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  customer_email text NOT NULL,
  preferred_date date NOT NULL,
  preferred_time text DEFAULT '',
  number_of_devotees int NOT NULL DEFAULT 1,
  amount numeric(10,2) DEFAULT NULL,
  customer_notes text DEFAULT '',
  admin_notes text DEFAULT '',
  cancellation_reason text DEFAULT '',
  status text NOT NULL DEFAULT 'PENDING',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_bookings" ON bookings;
CREATE POLICY "select_own_bookings" ON bookings FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_bookings" ON bookings;
CREATE POLICY "insert_own_bookings" ON bookings FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_bookings" ON bookings;
CREATE POLICY "update_own_bookings" ON bookings FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "admin_all_bookings" ON bookings;
CREATE POLICY "admin_all_bookings" ON bookings FOR ALL
  TO authenticated
  USING (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  WITH CHECK (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- ============================================================
-- 11. NOTIFICATIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  booking_id uuid REFERENCES bookings(id) ON DELETE SET NULL,
  type text NOT NULL DEFAULT 'booking_update',
  title text NOT NULL,
  message text NOT NULL,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_notifications" ON notifications;
CREATE POLICY "select_own_notifications" ON notifications FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_notifications" ON notifications;
CREATE POLICY "insert_own_notifications" ON notifications FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_notifications" ON notifications;
CREATE POLICY "update_own_notifications" ON notifications FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- BOOKING NUMBER GENERATION
-- ============================================================
CREATE OR REPLACE FUNCTION generate_booking_number()
RETURNS text AS $$
DECLARE
  current_year int := EXTRACT(YEAR FROM now());
  next_num int;
  booking_num text;
BEGIN
  SELECT COALESCE(MAX(num_seq), 0) + 1 INTO next_num
  FROM (
    SELECT
      CAST(
        SUBSTRING(booking_number FROM POSITION('-' IN booking_number) + 1 FOR LENGTH(booking_number) - POSITION('-' IN booking_number) - POSITION('-' IN REVERSE(booking_number)) + 2)
        AS int
      ) AS num_seq
    FROM bookings
    WHERE booking_number LIKE 'PP-' || current_year || '-%'
      AND booking_number ~ '^PP-[0-9]{4}-[0-9]{5}$'
  ) sub;

  booking_num := 'PP-' || current_year || '-' || lpad(next_num::text, 5, '0');
  RETURN booking_num;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to auto-generate booking number on insert
CREATE OR REPLACE FUNCTION set_booking_number()
RETURNS trigger AS $$
BEGIN
  IF NEW.booking_number IS NULL OR NEW.booking_number = '' THEN
    NEW.booking_number := generate_booking_number();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_set_booking_number ON bookings;
CREATE TRIGGER trigger_set_booking_number
  BEFORE INSERT ON bookings
  FOR EACH ROW EXECUTE FUNCTION set_booking_number();

-- ============================================================
-- UPDATED_AT TRIGGERS
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_user_profiles_updated_at ON user_profiles;
CREATE TRIGGER trigger_user_profiles_updated_at
  BEFORE UPDATE ON user_profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trigger_poojas_updated_at ON poojas;
CREATE TRIGGER trigger_poojas_updated_at
  BEFORE UPDATE ON poojas
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trigger_locations_updated_at ON locations;
CREATE TRIGGER trigger_locations_updated_at
  BEFORE UPDATE ON locations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trigger_states_updated_at ON states;
CREATE TRIGGER trigger_states_updated_at
  BEFORE UPDATE ON states
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trigger_location_poojas_updated_at ON location_poojas;
CREATE TRIGGER trigger_location_poojas_updated_at
  BEFORE UPDATE ON location_poojas
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trigger_bookings_updated_at ON bookings;
CREATE TRIGGER trigger_bookings_updated_at
  BEFORE UPDATE ON bookings
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_locations_state ON locations(state_id);
CREATE INDEX IF NOT EXISTS idx_locations_parent ON locations(parent_location_id);
CREATE INDEX IF NOT EXISTS idx_location_poojas_location ON location_poojas(location_id);
CREATE INDEX IF NOT EXISTS idx_location_poojas_pooja ON location_poojas(pooja_id);
CREATE INDEX IF NOT EXISTS idx_bookings_user ON bookings(user_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_number ON bookings(booking_number);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_poojas_slug ON poojas(slug);
CREATE INDEX IF NOT EXISTS idx_poojas_active ON poojas(is_active);

-- ============================================================
-- HELPER: Create notification when booking status changes
-- ============================================================
CREATE OR REPLACE FUNCTION create_booking_notification()
RETURNS trigger AS $$
DECLARE
  notif_title text;
  notif_message text;
  notif_type text;
BEGIN
  IF (TG_OP = 'UPDATE' AND NEW.status IS DISTINCT FROM OLD.status) THEN
    notif_type := 'booking_status_change';

    IF NEW.status = 'CONFIRMED' THEN
      notif_title := 'Booking Confirmed';
      notif_message := 'Your booking ' || NEW.booking_number || ' has been confirmed. Our team will contact you with further details.';
    ELSIF NEW.status = 'CANCELLED' THEN
      notif_title := 'Booking Cancelled';
      notif_message := COALESCE(NEW.cancellation_reason, 'Your booking ' || NEW.booking_number || ' has been cancelled.');
      IF NEW.cancellation_reason IS NOT NULL AND NEW.cancellation_reason != '' THEN
        notif_message := 'Your booking ' || NEW.booking_number || ' has been cancelled. Reason: ' || NEW.cancellation_reason;
      END IF;
    ELSIF NEW.status = 'COMPLETED' THEN
      notif_title := 'Pooja Completed';
      notif_message := 'Your booking ' || NEW.booking_number || ' has been marked as completed. Thank you for choosing Pooja Palace.';
    ELSE
      notif_title := 'Booking Updated';
      notif_message := 'Your booking ' || NEW.booking_number || ' status has been updated to ' || NEW.status || '.';
    END IF;

    INSERT INTO notifications (user_id, booking_id, type, title, message)
    VALUES (NEW.user_id, NEW.id, notif_type, notif_title, notif_message);
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_booking_notification ON bookings;
CREATE TRIGGER trigger_booking_notification
  AFTER UPDATE ON bookings
  FOR EACH ROW EXECUTE FUNCTION create_booking_notification();

-- ============================================================
-- HELPER: Auto-create user profile on signup
-- ============================================================
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $
BEGIN
  INSERT INTO public.user_profiles (user_id, email, name)
  VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data ->> 'name', ''));
  RETURN NEW;
END;
$;

DROP TRIGGER IF EXISTS trigger_handle_new_user ON auth.users;
CREATE TRIGGER trigger_handle_new_user
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();